language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - python -c "import bastion_ssh"
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
