language: python

python:
    - "2.7"

sudo: false
cache:
  pip: true

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi
install:
  - python scripts/ci/install.py
script: python scripts/ci/run-tests.py
after_success:
  - pip install python-coveralls && cd tests && coveralls
